// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://retstrxkoqtmwjyoqiqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJldHN0cnhrb3F0bXdqeW9xaXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODU2MDYsImV4cCI6MjA3MDE2MTYwNn0.ZGXI4iru-l_djlCIoS2R8arikrqo_ATTVQz09zWIW4Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});